#!/data/data/com.termux/files/usr/bin/bash
# By fmways
ALRC_HOME="$(cd -- "$(dirname -- "$(realpath "${BASH_SOURCE[0]}")")" &> /dev/null && pwd)"
VERSION="$(cat "${ALRC_HOME}/alrc-termux.sh" | sed -n 's/^# version : //p')"
CMD="$(basename -- $0)"

_usage() {
  echo -e "Usage :"
  echo -e "\t$CMD [command]"
  echo
  echo -e "Command :"
  echo -e " h\thelp\t\t display this message"
  echo -e " v\tversion\t\t display alrc-termux version"
  echo -e " i\tinstall\t\t install alrc-termux to your termux"
  echo -e " up\tupdate\t\t update alrc-termux"
  echo -e " un\tuninstall\t uninstall alrc-termux from your termux"
  echo -e " env\t\t\t display environment for alrc-termux"
  echo
  echo -e "Example :"
  echo -e "\t$CMD update"
  echo -e "\t$CMD uninstall"
  echo -e "\tsource <($CMD)"
}

_main() {

  case "$1" in
    h|help)
      _usage
      ;;
    v|version)
      echo $VERSION
      ;;
    i|install)
      $ALRC_HOME/install.sh
      ;;
    up|update)
      $ALRC_HOME/update.sh
      ;;
    un|uninstall)
      $ALRC_HOME/uninstall.sh
      ;;
    env)
      source $ALRC_HOME/env.sh
      ;;
    *)
      echo "Unknown arguments" > /dev/stderr
      _usage
      return 1;;
  esac

}

_main $@
